"""SuperSplat loader tests."""

import struct

from tigas.renderer.supersplat_loader import load_supersplat_compressed_ply


def _pack_position(x_q: int, y_q: int, z_q: int) -> int:
    return (x_q & 0x3FF) | ((y_q & 0x3FF) << 10) | ((z_q & 0x3FF) << 20)


def _pack_color(r_q: int, g_q: int, b_q: int, a_q: int) -> int:
    return (
        (r_q & 0xFF)
        | ((g_q & 0xFF) << 8)
        | ((b_q & 0xFF) << 16)
        | ((a_q & 0xFF) << 24)
    )


def test_load_supersplat_compressed_ply(tmp_path) -> None:
    ply_path = tmp_path / "mini.compressed.ply"
    header = "\n".join(
        [
            "ply",
            "format binary_little_endian 1.0",
            "comment Generated by SuperSplat 2.4.1",
            "element chunk 1",
            "property float min_x",
            "property float min_y",
            "property float min_z",
            "property float max_x",
            "property float max_y",
            "property float max_z",
            "property float min_scale_x",
            "property float min_scale_y",
            "property float min_scale_z",
            "property float max_scale_x",
            "property float max_scale_y",
            "property float max_scale_z",
            "property float min_r",
            "property float min_g",
            "property float min_b",
            "property float max_r",
            "property float max_g",
            "property float max_b",
            "element vertex 2",
            "property uint packed_position",
            "property uint packed_rotation",
            "property uint packed_scale",
            "property uint packed_color",
            "end_header",
            "",
        ]
    ).encode("ascii")

    chunk = struct.pack(
        "<18f",
        -1.0,
        -2.0,
        -3.0,
        1.0,
        2.0,
        3.0,
        0.0,
        0.0,
        0.0,
        1.0,
        1.0,
        1.0,
        0.0,
        0.0,
        0.0,
        1.0,
        1.0,
        1.0,
    )
    vertex_a = struct.pack(
        "<4I",
        _pack_position(0, 0, 0),
        0,
        0,
        _pack_color(0, 0, 0, 255),
    )
    vertex_b = struct.pack(
        "<4I",
        _pack_position(1023, 1023, 1023),
        0,
        0,
        _pack_color(255, 255, 255, 255),
    )
    ply_path.write_bytes(header + chunk + vertex_a + vertex_b)

    cloud = load_supersplat_compressed_ply(str(ply_path))
    assert cloud.point_count == 2
    assert cloud.xyz.shape == (2, 3)
    assert cloud.rgb.shape == (2, 3)
    assert cloud.xyz[0, 0] == -1.0
    assert cloud.xyz[1, 2] == 3.0
